name: MaSuiteHomesBridge
main: fi.matiaspaavilainen.masuitehomes.MaSuiteHomes
version: 1.2.5.1
author: Masagameplay
commands:
  sethome:
    description: Sets home point
    aliases: [createhome, homeset]
    permission: masuitehomes.home.set
  delhome:
    description: Deletes home point
    aliases: [deletehome, homedel]
    permission: masuitehomes.home.delete
  home:
    description: Teleports to home point
    permission: masuitehomes.home.teleport
  homes:
    description: Lists all available homes
    aliases: [homelist, listhomes]
    permission: masuitehomes.home.list